name: python lint check
  
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  xmllint:
    name: Run python lint check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install pylint python3-lxml python3-requests python3-gi python3-gst-1.0

      - name: Run pylint 
        run: |
          pylint cgiexecute mediastream screenshot setbackground setringtone xmlinfo 
