name: python lint
  
on:
  push:
    branches:
      - master
    paths:
      - 'cgiexecute'
      - 'mediastream'
      - 'screenshot'
      - 'setbackground'
      - 'setringtone'
      - 'xmlinfo'
      - '.github/workflows/pylint.yml'

  pull_request:
    branches:
      - master
    paths:
      - 'cgiexecute'
      - 'mediastream'
      - 'screenshot'
      - 'setbackground'
      - 'setringtone'
      - 'xmlinfo'
      - '.github/workflows/pylint.yml'

jobs:
  lint:
    name: Run python linter 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt install pylint python3-lxml python3-requests python3-gi python3-gst-1.0

      - name: Run pylint 
        run: |
          pylint cgiexecute mediastream screenshot setbackground setringtone xmlinfo 
